// Books Action Types
export const READ_BOOKS_SUCCESFUL = "READ_BOOKS_SUCCESFUL";
export const READ_BOOKS_PENDING = "READ_BOOKS_PENDING";
export const READ_BOOKS_FAILURE = "READ_BOOKS_FAILURE";
export const ADD_BOOKS_SUCCESFUL = "ADD_BOOKS_SUCCESFUL";
export const ADD_BOOKS_PENDING = "ADD_BOOKS_PENDING";
export const ADD_BOOKS_FAILURE = "ADD_BOOKS_FAILURE";
export const UPDATE_BOOKS_SUCCESFUL = "UPDATE_BOOKS_SUCCESFUL";
export const UPDATE_BOOKS_PENDING = "UPDATE_BOOKS_PENDING";
export const UPDATE_BOOKS_FAILURE = "UPDATE_BOOKS_FAILURE";
export const DELETE_BOOKS_SUCCESFUL = "DELETE_BOOKS_SUCCESFUL";
export const DELETE_BOOKS_PENDING = "DELETE_BOOKS_PENDING";
export const DELETE_BOOKS_FAILURE = "DELETE_BOOKS_FAILURE";

// Branches Action Types
export const READ_BRANCHES_SUCCESSFUL = "READ_BRANCHES_SUCCESSFUL";
export const READ_BRANCHES_PENDING = "READ_BRANCHES_PENDING";
export const READ_BRANCHES_FAILURE = "READ_BRANCHES_FAILURE";
export const ADD_BRANCHES_SUCCESSFUL = "ADD_BRANCHES_SUCCESSFUL";
export const ADD_BRANCHES_PENDING = "ADD_BRANCHES_PENDING";
export const ADD_BRANCHES_FAILURE = "ADD_BRANCHES_FAILURE";
export const UPDATE_BRANCHES_SUCCESSFUL = "UPDATE_BRANCHES_SUCCESSFUL";
export const UPDATE_BRANCHES_PENDING = "UPDATE_BRANCHES_PENDING";
export const UPDATE_BRANCHES_FAILURE = "UPDATE_BRANCHES_FAILURE";
export const DELETE_BRANCHES_SUCCESSFUL = "DELETE_BRANCHES_SUCCESSFUL";
export const DELETE_BRANCHES_PENDING = "DELETE_BRANCHES_PENDING";
export const DELETE_BRANCHES_FAILURE = "DELETE_BRANCHES_FAILURE";

//Genres Action Types
export const READ_GENRES_SUCCESFUL = "READ_GENRES_SUCCESFUL";
export const READ_GENRES_PENDING = "READ_GENRES_PENDING";
export const READ_GENRES_FAILURE = "READ_GENRES_FAILURE";
export const CREATE_GENRES_SUCCESFUL = "CREATE_GENRES_SUCCESFUL";
export const CREATE_GENRES_PENDING = "CREATE_GENRES_PENDING";
export const CREATE_GENRES_FAILURE = "CREATE_GENRES_FAILURE";
export const UPDATE_GENRES_SUCCESFUL = "UPDATE_GENRES_SUCCESFUL";
export const UPDATE_GENRES_PENDING = "UPDATE_GENRES_PENDING";
export const UPDATE_GENRES_FAILURE = "UPDATE_GENRES_FAILURE";
export const DELETE_GENRES_SUCCESFUL = "DELETE_GENRES_SUCCESFUL";
export const DELETE_GENRES_PENDING = "DELETE_GENRES_PENDING";
export const DELETE_GENRES_FAILURE = "DELETE_GENRES_FAILURE";

//Borrower Action Types
export const READ_BORROWERS_SUCCESFUL = "READ_BORROWERS_SUCCESFUL";
export const READ_BORROWERS_PENDING = "READ_BORROWERS_PENDING";
export const READ_BORROWERS_FAILURE = "READ_BORROWERS_FAILURE";
export const CREATE_BORROWERS_SUCCESFUL = "CREATE_BORROWERS_SUCCESFUL";
export const CREATE_BORROWERS_PENDING = "CREATE_BORROWERS_PENDING";
export const CREATE_BORROWERS_FAILURE = "CREATE_BORROWERS_FAILURE";
export const UPDATE_BORROWERS_SUCCESFUL = "UPDATE_BORROWERS_SUCCESFUL";
export const UPDATE_BORROWERS_PENDING = "UPDATE_BORROWERS_PENDING";
export const UPDATE_BORROWERS_FAILURE = "UPDATE_BORROWERS_FAILURE";
export const DELETE_BORROWERS_SUCCESFUL = "DELETE_BORROWERS_SUCCESFUL";
export const DELETE_BORROWERS_PENDING = "DELETE_BORROWERS_PENDING";
export const DELETE_BORROWERS_FAILURE = "DELETE_BORROWERS_FAILURE";
